In [1]:
!git clone https://github.com/ByungHeonLEE/ml_python.git

Cloning into 'ml_python'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (15/15), done.
remote: Total 16 (delta 1), reused 15 (delta 0), pack-reused 0
Unpacking objects: 100% (16/16), done.


In [32]:
####pandas
import pandas as pd

In [6]:
#파일들로부터 데이터 읽어오기 
파일경로 = 'ml_python/csv/lemonade.csv'
레모네이드 = pd.read_csv(파일경로)

In [7]:
#파일들로부터 데이터 읽어오기 
파일경로 = 'ml_python/csv/boston.csv'
보스턴 = pd.read_csv(파일경로)

In [8]:
#파일들로부터 데이터 읽어오기 
파일경로 = 'ml_python/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)

In [10]:
#데이터 모양으로 확인하기
print(레모네이드.shape)
print(보스턴.shape)
print(아이리스.shape)

(6, 2)
(506, 14)
(150, 5)


In [11]:
#칼럼이름 출력
print(레모네이드.columns)
print(보스턴.columns)
print(아이리스.columns)

Index(['온도', '판매량'], dtype='object')
Index(['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat', 'medv'],
      dtype='object')
Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종'], dtype='object')


In [15]:
독립 = 레모네이드[['온도']]
종속 = 레모네이드[['판매량']]
print(독립.shape, 종속.shape)

독립 = 보스턴[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = 보스턴[['medv']]
print(독립.shape, 종속.shape)

독립 = 아이리스[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 아이리스[['품종']]
print(독립.shape, 종속.shape)

(6, 1) (6, 1)
(506, 13) (506, 1)
(150, 4) (150, 1)


In [16]:
레모네이드.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [17]:
#라이브러리 사용
import tensorflow as tf
import pandas as pd

In [19]:
#데이터 준비 
file_path = 'ml_python/csv/lemonade.csv'
data = pd.read_csv(file_path)
data.head()

온도  판매량
0  20   40
1  21   42
2  22   44
3  23   46
4  24   48

In [20]:
ind = data[['온도']]
dep = data[['판매량']]

print(ind.shape, dep.shape)

(6, 1) (6, 1)


In [22]:
#모델을 만드다
X = tf.keras.layers.Input(shape=[1])
Y = tf.keras.layers.Dense(1)(X)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [28]:
#학습
model.fit(ind, dep, epochs=10000, verbose=0)

In [29]:
model.fit(ind, dep, epochs=10)
#유효숫자, 0에가까운 모델

Epoch 1/10
1/1 [==============================] - 0s 4ms/step - loss: 2.5766e-04
Epoch 2/10
1/1 [==============================] - 0s 6ms/step - loss: 2.5767e-04
Epoch 3/10
1/1 [==============================] - 0s 6ms/step - loss: 2.5757e-04
Epoch 4/10
1/1 [==============================] - 0s 4ms/step - loss: 2.5740e-04
Epoch 5/10
1/1 [==============================] - 0s 4ms/step - loss: 2.5724e-04
Epoch 6/10
1/1 [==============================] - 0s 4ms/step - loss: 2.5709e-04
Epoch 7/10
1/1 [==============================] - 0s 4ms/step - loss: 2.5692e-04
Epoch 8/10
1/1 [==============================] - 0s 10ms/step - loss: 2.5682e-04
Epoch 9/10
1/1 [==============================] - 0s 3ms/step - loss: 2.5663e-04
Epoch 10/10
1/1 [==============================] - 0s 3ms/step - loss: 2.5659e-04


In [30]:
model.predict(ind)

array([[40.02713 ],
       [42.021294],
       [44.015453],
       [46.009613],
       [48.003773],
       [49.997932]], dtype=float32)

In [31]:
model.predict([[15]])

array([[30.056332]], dtype=float32)

두번째 딥러닝 보스턴

In [33]:
#2번째 딥러닝, 보스턴
#데이터 준비 
file_path = 'ml_python/csv/boston.csv'
data = pd.read_csv(file_path)
data.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [34]:
#독립변수, 종속변수 분리
독립 = data[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = data[['medv']]

print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [35]:
#모델의 구조
X = tf.keras.layers.Input(shape=[13])
#입력층이 13개, 독립변수가 13개기 때문에
Y = tf.keras.layers.Dense(1)(X)
#1개, 종속변수의 feature가 하나니까 하나를 만드는 구조
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')
#w를 찾는 것(weight) 현재 모델에서는 뉴런(퍼셉트론)

In [40]:
model.fit(독립, 종속, epochs=1000, verbose=0)

In [43]:
model.predict(독립[5:10])

array([[24.707363],
       [20.506886],
       [17.384853],
       [ 9.043344],
       [16.86159 ]], dtype=float32)

In [44]:
종속[5:10]

medv
5  28.7
6  22.9
7  27.1
8  16.5
9  18.9

In [45]:
#모델의 수식확인
model.get_weights()

[array([[-0.09278402],
        [ 0.0539563 ],
        [-0.04279294],
        [ 2.9425375 ],
        [ 1.355038  ],
        [ 5.0415845 ],
        [-0.00802728],
        [-0.9963507 ],
        [ 0.17349704],
        [-0.01147194],
        [-0.33483425],
        [ 0.01252307],
        [-0.49320862]], dtype=float32), array([4.1984053], dtype=float32)]

집값 = -0.09278402x1+
        0.0539563x2+
        -0.04279294x3+
        2.9425375x4+
        1.355038x5+
        5.0415845x6+
        -0.00802728x7+
        -0.9963507x8+
        0.17349704x9+
        -0.01147194x10+
        -0.33483425x11+
        0.01252307x12+
        -0.49320862x13

세번째 아이리스(붓꽃)

In [115]:
#범주형 종속변수, 분류 가능
파일경로 = 'ml_python/csv/iris.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭      품종
0   5.1  3.5    1.4   0.2  setosa
1   4.9  3.0    1.4   0.2  setosa
2   4.7  3.2    1.3   0.2  setosa
3   4.6  3.1    1.5   0.2  setosa
4   5.0  3.6    1.4   0.2  setosa

In [116]:
#원핫 인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_setosa  품종_versicolor  품종_virginica
0   5.1  3.5    1.4   0.2          1              0             0
1   4.9  3.0    1.4   0.2          1              0             0
2   4.7  3.2    1.3   0.2          1              0             0
3   4.6  3.1    1.5   0.2          1              0             0
4   5.0  3.6    1.4   0.2          1              0             0

In [117]:
print(인코딩.columns)

독립 = 인코딩[['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭']]
종속 = 인코딩[['품종_setosa', '품종_versicolor','품종_virginica']]

print(독립.shape, 종속.shape)

Index(['꽃잎길이', '꽃잎폭', '꽃받침길이', '꽃받침폭', '품종_setosa', '품종_versicolor',
       '품종_virginica'],
      dtype='object')
(150, 4) (150, 3)


In [126]:
#모델
X = tf.keras.layers.Input(shape=[4])

H = tf.keras.layers.Dense(8)(X)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

H = tf.keras.layers.Dense(8)(H)
H = tf.keras.layers.BatchNormalization()(H)
H = tf.keras.layers.Activation('swish')(H)

Y = tf.keras.layers.Dense(3, activation='softmax')(H)
model = tf.keras.models.Model(X, Y)
model.compile(loss='categorical_crossentropy', metrics='accuracy')

In [154]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0469 - accuracy: 0.9733
Epoch 2/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0408 - accuracy: 0.9733
Epoch 3/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0614 - accuracy: 0.9733
Epoch 4/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0395 - accuracy: 0.9800
Epoch 5/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0321 - accuracy: 0.9800
Epoch 6/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0393 - accuracy: 0.9800
Epoch 7/10
5/5 [==============================] - 0s 2ms/step - loss: 0.0418 - accuracy: 0.9933
Epoch 8/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0714 - accuracy: 0.9667
Epoch 9/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0248 - accuracy: 0.9933
Epoch 10/10
5/5 [==============================] - 0s 3ms/step - loss: 0.0387 - accuracy: 0.9800


In [94]:
#모델 이용
model.predict(독립[-5:])

array([[1.0746601e-05, 1.8075317e-02, 9.8191398e-01],
       [7.2105344e-05, 8.0899812e-02, 9.1902810e-01],
       [3.7858004e-05, 5.6936003e-02, 9.4302613e-01],
       [1.5890625e-06, 1.5515898e-03, 9.9844688e-01],
       [3.3601700e-05, 3.0065628e-02, 9.6990079e-01]], dtype=float32)

In [95]:
print(종속[-5:])

     품종_setosa  품종_versicolor  품종_virginica
145          0              0             1
146          0              0             1
147          0              0             1
148          0              0             1
149          0              0             1


In [ ]:
#가중치 출력
model.get_weights()

In [97]:
model.summary()

Model: "model_6"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_8 (InputLayer)         [(None, 4)]               0         
_________________________________________________________________
dense_10 (Dense)             (None, 8)                 40        
_________________________________________________________________
dense_11 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_12 (Dense)             (None, 8)                 72        
_________________________________________________________________
dense_13 (Dense)             (None, 3)                 27        
Total params: 211
Trainable params: 211
Non-trainable params: 0
_________________________________________________________________


히든레이어

In [109]:
#데이터 준비 
file_path = 'ml_python/csv/boston.csv'
data = pd.read_csv(file_path)
data.head()

crim    zn  indus  chas    nox  ...  tax  ptratio       b  lstat  medv
0  0.00632  18.0   2.31     0  0.538  ...  296     15.3  396.90   4.98  24.0
1  0.02731   0.0   7.07     0  0.469  ...  242     17.8  396.90   9.14  21.6
2  0.02729   0.0   7.07     0  0.469  ...  242     17.8  392.83   4.03  34.7
3  0.03237   0.0   2.18     0  0.458  ...  222     18.7  394.63   2.94  33.4
4  0.06905   0.0   2.18     0  0.458  ...  222     18.7  396.90   5.33  36.2

[5 rows x 14 columns]

In [110]:
독립 = data[['crim', 'zn', 'indus', 'chas', 'nox', 'rm', 'age', 'dis', 'rad', 'tax',
       'ptratio', 'b', 'lstat']]
종속 = data[['medv']]

print(독립.shape, 종속.shape)

(506, 13) (506, 1)


In [111]:
#모델의 구조
X = tf.keras.layers.Input(shape=[13])

H1 = tf.keras.layers.Dense(10, activation='swish')(X)

H2 = tf.keras.layers.Dense(10)(H1)
H2 = tf.keras.layers.BatchNormalization()(H2)
H2 = tf.keras.layers.Activation('swish')(H2)

#H1과 H2는 같은 것
Y = tf.keras.layers.Dense(1)(H2)
model = tf.keras.models.Model(X, Y)
model.compile(loss='mse')

In [71]:
model.summary()
#param은 항이 13개, 그리고 bias 14개가 10개 생겼으니 140
# 그다음은 10개를 1개 = 11개

Model: "model_4"
_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_6 (InputLayer)         [(None, 13)]              0         
_________________________________________________________________
dense_4 (Dense)              (None, 10)                140       
_________________________________________________________________
dense_5 (Dense)              (None, 1)                 11        
Total params: 151
Trainable params: 151
Non-trainable params: 0
_________________________________________________________________


In [114]:
model.fit(독립, 종속, epochs=10)

Epoch 1/10
16/16 [==============================] - 0s 1ms/step - loss: 16.7390
Epoch 2/10
16/16 [==============================] - 0s 1ms/step - loss: 14.8149
Epoch 3/10
16/16 [==============================] - 0s 1ms/step - loss: 16.0320
Epoch 4/10
16/16 [==============================] - 0s 1ms/step - loss: 15.9802
Epoch 5/10
16/16 [==============================] - 0s 1ms/step - loss: 14.4947
Epoch 6/10
16/16 [==============================] - 0s 1ms/step - loss: 14.6185
Epoch 7/10
16/16 [==============================] - 0s 1ms/step - loss: 19.3590
Epoch 8/10
16/16 [==============================] - 0s 2ms/step - loss: 16.7043
Epoch 9/10
16/16 [==============================] - 0s 1ms/step - loss: 18.0098
Epoch 10/10
16/16 [==============================] - 0s 2ms/step - loss: 15.0601


In [81]:
print(model.predict(독립[:5]))
print(종속[:5])

[[30.85561 ]
 [20.2296  ]
 [32.08653 ]
 [34.300438]
 [30.456995]]
   medv
0  24.0
1  21.6
2  34.7
3  33.4
4  36.2


In [98]:
import pandas as pd

In [99]:
파일경로 = 'ml_python/csv/iris2.csv'
아이리스 = pd.read_csv(파일경로)
아이리스.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종
0   5.1  3.5    1.4   0.2   0
1   4.9  3.0    1.4   0.2   0
2   4.7  3.2    1.3   0.2   0
3   4.6  3.1    1.5   0.2   0
4   5.0  3.6    1.4   0.2   0

In [100]:
#원핫
인코딩 = pd.get_dummies(아이리스)
인코딩.head()
#왜 안되냐면, 현재 품종을 범주형인지 모른다, 수치형인지 아는듯

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종
0   5.1  3.5    1.4   0.2   0
1   4.9  3.0    1.4   0.2   0
2   4.7  3.2    1.3   0.2   0
3   4.6  3.1    1.5   0.2   0
4   5.0  3.6    1.4   0.2   0

In [101]:
print(아이리스.dtypes)
#품종이 int네

꽃잎길이     float64
꽃잎폭      float64
꽃받침길이    float64
꽃받침폭     float64
품종         int64
dtype: object


In [103]:
#품종 타입을 범주형으로 변화시켜야 한다 
아이리스['품종'] = 아이리스['품종'].astype('category')
print(아이리스.dtypes)

꽃잎길이      float64
꽃잎폭       float64
꽃받침길이     float64
꽃받침폭      float64
품종       category
dtype: object


In [104]:
#원핫인코딩
인코딩 = pd.get_dummies(아이리스)
인코딩.head()

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭  품종_0  품종_1  품종_2
0   5.1  3.5    1.4   0.2     1     0     0
1   4.9  3.0    1.4   0.2     1     0     0
2   4.7  3.2    1.3   0.2     1     0     0
3   4.6  3.1    1.5   0.2     1     0     0
4   5.0  3.6    1.4   0.2     1     0     0

In [105]:
아이리스.isna().sum()

꽃잎길이     0
꽃잎폭      1
꽃받침길이    0
꽃받침폭     0
품종       0
dtype: int64

In [106]:
아이리스.tail()
#nan not available

꽃잎길이  꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.0    5.2   2.3  2
146   6.3  2.5    5.0   1.9  2
147   6.5  3.0    5.2   2.0  2
148   6.2  3.4    5.4   2.3  2
149   5.9  NaN    5.1   1.8  2

In [108]:
#na값에 꽃잎폭 평균값을 넣어주는 방법
mean = 아이리스['꽃잎폭'].mean()
아이리스['꽃잎폭'] = 아이리스['꽃잎폭'].fillna(mean)
아이리스.tail()

꽃잎길이       꽃잎폭  꽃받침길이  꽃받침폭 품종
145   6.7  3.000000    5.2   2.3  2
146   6.3  2.500000    5.0   1.9  2
147   6.5  3.000000    5.2   2.0  2
148   6.2  3.400000    5.4   2.3  2
149   5.9  3.054362    5.1   1.8  2